# --- !Ups

create table "users" (
  "id" int(10) generated by default as identity(start with 1) not null primary key,
  "email" varchar(255) not null,
  "password" varchar(255) not null,
  "username" varchar(255) not null
);

create table "posts" (
  "id" int(10) generated by default as identity(start with 1) not null primary key,
  "user_id" int(10) not null,
  "message" varchar(255) not null,
  "create_at" datetime not null
);

insert into ("id", "user_id", "message", "create_at") values ("1", "1", "test message.", "2015-10-05 01:09:00")

# --- !Downs

drop table "users" if exists;
drop table "posts" if exists;
