# --- !Ups

create table "users" (
  "id" int(10) generated by default as identity(start with 1) not null primary key,
  "email" varchar(255) not null,
  "password" varchar(255) not null,
  "username" varchar(255) not null
);

# --- !Downs

drop table "users" if exists;
